//==================================================================================================
//Version 1.0, auto-generated.
//Generated By liuyx.
//Date: 2012-4-17 9:26:23.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.Basic.API.Entity.ClassRoom;
using ETMS.Components.Basic.Implement.DAL.ClassRoom;
using System.Transactions;
namespace ETMS.Components.Basic.Implement.BLL.ClassRoom
{
    /// <summary>
    /// 教室表业务逻辑
    /// </summary>
    public partial class Res_ClassRoomLogic
	{
		private static readonly Res_ClassRoomDataAccess DAL = new Res_ClassRoomDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(Res_ClassRoom res_ClassRoom)
		{
			DAL.Add(res_ClassRoom);
            BizLogHelper.AddOperate(res_ClassRoom);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(Res_ClassRoom res_ClassRoom)
		{
            //修改前信息
            Res_ClassRoom originalEntity=GetById(res_ClassRoom.ClassRoomID);
			DAL.Save(res_ClassRoom);
            BizLogHelper.UpdateOperate(originalEntity,res_ClassRoom);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Guid classRoomID)
		{
            doRemove(classRoomID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Guid[] classRoomIDs)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (Guid id in classRoomIDs  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public Res_ClassRoom GetById(Guid classRoomID)
		{
			Res_ClassRoom res_ClassRoom = DAL.GetById(classRoomID);
			if (res_ClassRoom == null)
			{
				throw new ETMS.AppContext.BusinessException("Res_ClassRoom.Res_ClassRoom.NotFoundException",new object[]{classRoomID});
			}
			
			return res_ClassRoom;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<Res_ClassRoom> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

