//==================================================================================================
//Version 1.0, auto-generated.
//Generated By liuyx.
//Date: 2012-4-17 9:26:23.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using ETMS.Utility;
using ETMS.Utility.Logging;
using ETMS.Components.Basic.API.Entity.ClassRoom;
using ETMS.Components.Basic.API;
namespace ETMS.Components.Basic.Implement.BLL.ClassRoom
{
    /// <summary>
    /// 教室表业务逻辑
    /// </summary>
    public partial class Res_ClassRoomLogic
	{
 		/// <summary>
		/// 保存操作
		/// </summary>
		public void Save(Res_ClassRoom res_ClassRoom)
		{
            try
            {
			    if(res_ClassRoom.ClassRoomID.IsEmpty())
                {
                    //设置主键ID（仅类型为GUID有效，Int型则由数据库自增产生）
                    res_ClassRoom.ClassRoomID=res_ClassRoom.ClassRoomID.NewID();;
                    Add(res_ClassRoom);
                }
                else
                {
                    Update(res_ClassRoom);
                }
            }
           catch (System.Data.SqlClient.SqlException ex)
            {
                //枚举数据约束异常并转换为业务异常Index_U_ClassRoomName
                if (ex.Message.IndexOf("Index_U_ClassRoomCode",StringComparison.InvariantCultureIgnoreCase) != -1)
                {
				    throw new ETMS.AppContext.BusinessException(BizErrorDefine.Res_ClassRoom_Res_ClassRoom_CodeExists);
                }
                else if (ex.Message.IndexOf("Index_U_ClassRoomName",StringComparison.InvariantCultureIgnoreCase) != -1)
                {
                    throw new ETMS.AppContext.BusinessException(BizErrorDefine.Res_ClassRoom_Res_ClassRoom_NameExists);
                }
                //如果仍未处理，则抛出
                throw ex;
            } 
		} 

        /// <summary>
		/// 删除
		/// </summary>
		public void doRemove(Guid classRoomID)
		{
            try
            {
			     DAL.Remove(classRoomID);
                 //记录删除日志（根据ID删除）
                 BizLogHelper.Operate(classRoomID,"删除");
            }
           catch (System.Data.SqlClient.SqlException ex)
            {
                //枚举数据约束异常并转换为业务异常，数据已经使用
                if (ex.Message.IndexOf("FK_",StringComparison.InvariantCultureIgnoreCase) != -1)
                {
				    throw new ETMS.AppContext.BusinessException(string.Format(BizErrorDefine.Res_ClassRoom_Res_ClassRoom_DataUsed, GetById(classRoomID).ClassRoomName));
                } 
                //如果仍未处理，则抛出
                throw ex;
            }  
		}  
	}
	
	
}

