//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-5-6 11:46:50.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;

using ETMS.AppContext;
namespace ETMS.Components.IDP.API.Entity
{
    /// <summary>
    /// IDP计划学习内容明细表业务实体
    /// </summary>
    [Serializable]
	public partial class IDP_PlanContentDetail:AbstractObject
	{ 	
        #region 所有业务基类
		 
        public override string DefaultKeyName
        {
            get { return "PlanContentDetailID"; }
        }
         public override object KeyValue
        {
            get
            {
                return this.PlanContentDetailID; 
            }
            set
            {
                this.PlanContentDetailID=(Guid)value;
            }
        }    
	    #endregion

		#region Fields, Properties
		/// <summary>
		/// IDP计划学习内容明细ID
		/// </summary>
		public Guid PlanContentDetailID{get;set;} 
		
		/// <summary>
		/// IDP计划学习内容ID
		/// </summary>
		public Guid IDPPlanContentID{get;set;} 
		
		/// <summary>
		/// IDP学习内容来源
		/// </summary>
		public Int32 IDPSourceID{get;set;} 
		
		/// <summary>
		/// IDP学习内容来源ID
		/// </summary>
		public String IDPPlanContentSourceID{get;set;} 
		
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public String CreateUser{get;set;} 
		
		/// <summary>
		/// 创建人ID
		/// </summary>
		public Int32 CreateUserID{get;set;} 
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime ModifyTime{get;set;} 
		
		/// <summary>
		/// 修改人
		/// </summary>
		public String ModifyUser{get;set;} 
		
		/// <summary>
		/// 备注
		/// </summary>
		public String Remark{get;set;} 
		
		#endregion Fields, Properties

	}
}
