//==================================================================================================
//Version 1.0, auto-generated.
//Generated By huangzf.
//Date: 2013-1-24 10:33:04.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.QS.API.Entity;
using ETMS.Components.QS.Implement.DAL;
using System.Transactions;
namespace ETMS.Components.QS.Implement.BLL
{
    /// <summary>
    /// 问卷调查题目表业务逻辑
    /// </summary>
    public partial class QS_QueryTitleLogic
	{
		private static readonly QS_QueryTitleDataAccess DAL = new QS_QueryTitleDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(QS_QueryTitle qS_QueryTitle)
		{
			DAL.Add(qS_QueryTitle);
            BizLogHelper.AddOperate(qS_QueryTitle);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(QS_QueryTitle qS_QueryTitle)
		{
            //修改前信息
            QS_QueryTitle originalEntity=GetById(qS_QueryTitle.TitleID);
			DAL.Save(qS_QueryTitle);
            BizLogHelper.UpdateOperate(originalEntity,qS_QueryTitle);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Guid titleID)
		{
            doRemove(titleID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Guid[] titleIDs)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (Guid id in titleIDs  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public QS_QueryTitle GetById(Guid titleID)
		{
			QS_QueryTitle qS_QueryTitle = DAL.GetById(titleID);
			if (qS_QueryTitle == null)
			{
				throw new ETMS.AppContext.BusinessException(".QS_QueryTitle.NotFoundException",new object[]{titleID});
			}
			
			return qS_QueryTitle;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<QS_QueryTitle> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

