//==================================================================================================
//Version 1.0, auto-generated.
//Generated By huangzf.
//Date: 2013-1-24 10:33:04.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1), a product of ZhouYonghua(Zhou_Yonghua@163.com).
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.QS.API.Entity;
using ETMS.Components.QS.Implement.DAL;
namespace ETMS.Components.QS.Implement.BLL
{
    /// <summary>
    /// 问卷调查题目选择题选项表业务逻辑
    /// </summary>
    public partial class QS_QueryTitleOptionLogic
	{
		private static readonly QS_QueryTitleOptionDataAccess DAL = new QS_QueryTitleOptionDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(QS_QueryTitleOption qS_QueryTitleOption)
		{
			DAL.Add(qS_QueryTitleOption);
            BizLogHelper.AddOperate(qS_QueryTitleOption);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(QS_QueryTitleOption qS_QueryTitleOption)
		{
            //修改前信息
            QS_QueryTitleOption originalEntity=GetById(qS_QueryTitleOption.OptionID);
			DAL.Save(qS_QueryTitleOption);
            BizLogHelper.UpdateOperate(originalEntity,qS_QueryTitleOption);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Guid optionID)
		{
            doRemove(optionID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Guid[] optionIDs)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (Guid id in optionIDs  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public QS_QueryTitleOption GetById(Guid optionID)
		{
			QS_QueryTitleOption qS_QueryTitleOption = DAL.GetById(optionID);
			if (qS_QueryTitleOption == null)
			{
				throw new ETMS.AppContext.BusinessException(".QS_QueryTitleOption.NotFoundException",new object[]{optionID});
			}
			
			return qS_QueryTitleOption;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<QS_QueryTitleOption> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

