//==================================================================================================
//Version 1.0, auto-generated.
//Generated By huangzf.
//Date: 2013-1-24 10:33:04.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.QS.API.Entity;
using ETMS.Components.QS.Implement.DAL;
namespace ETMS.Components.QS.Implement.BLL
{
    /// <summary>
    /// 问卷调查范围业务逻辑
    /// </summary>
    public partial class QS_QueryAreaLogic
	{
		private static readonly QS_QueryAreaDataAccess DAL = new QS_QueryAreaDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(QS_QueryArea qS_QueryArea)
		{
			DAL.Add(qS_QueryArea);
            BizLogHelper.AddOperate(qS_QueryArea);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(QS_QueryArea qS_QueryArea)
		{
            //修改前信息
            QS_QueryArea originalEntity=GetById(qS_QueryArea.QueryAreaID);
			DAL.Save(qS_QueryArea);
            BizLogHelper.UpdateOperate(originalEntity,qS_QueryArea);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Guid queryAreaID)
		{
            doRemove(queryAreaID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Guid[] queryAreaIDs)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (Guid id in queryAreaIDs  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public QS_QueryArea GetById(Guid queryAreaID)
		{
			QS_QueryArea qS_QueryArea = DAL.GetById(queryAreaID);
			if (qS_QueryArea == null)
			{
				throw new ETMS.AppContext.BusinessException(".QS_QueryArea.NotFoundException",new object[]{queryAreaID});
			}
			
			return qS_QueryArea;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<QS_QueryArea> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

