//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-4-2 11:05:29.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.Basic.API.Entity.Import;
using ETMS.Components.Basic.Implement.DAL.Import;
namespace ETMS.Components.Basic.Implement.BLL.Import
{
    /// <summary>
    /// 数据导入任务业务逻辑
    /// </summary>
    public partial class Import_TaskLogic
	{
		private static readonly Import_TaskDataAccess DAL = new Import_TaskDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(Import_Task import_Task)
		{
			DAL.Add(import_Task);
            BizLogHelper.AddOperate(import_Task);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Int32 taskID)
		{
            doRemove(taskID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Int32[] taskIDs)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (Int32 id in taskIDs  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
		/// <summary>
		/// 保存
		/// </summary>
		public void Update(Import_Task import_Task)
		{
            //修改前信息
            Import_Task originalEntity=GetById(import_Task.TaskID);
			DAL.Save(import_Task);
            BizLogHelper.UpdateOperate(originalEntity,import_Task);
		}
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public Import_Task GetById(Int32 taskID)
		{
			Import_Task import_Task = DAL.GetById(taskID);
			if (import_Task == null)
			{
				throw new ETMS.AppContext.BusinessException("Import.Import_Task.NotFoundException",new object[]{taskID});
			}
			
			return import_Task;
		}		
		 
		/// <summary>
        	/// 查询分页数据
        	/// </summary>
        	/// <param name="pageIndex">页号</param>
        	/// <param name="pageSize">页面大小</param>
        	/// <param name="sortExpression">排序条件</param>
        	/// <param name="criteria">筛选条件</param>
        	/// <param name="totalRecords">out 记录总数</param>
        	/// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

