//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-4-13 20:34:59.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.Basic.API.Entity.Security;
using ETMS.Components.Basic.Implement.DAL.Security;
namespace ETMS.Components.Basic.Implement.BLL.Security
{
    /// <summary>
    /// 业务操作日志业务逻辑
    /// </summary>
    public partial class Log_BusinessOperateLogic
	{
		private static readonly Log_BusinessOperateDataAccess DAL = new Log_BusinessOperateDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(Log_BusinessOperate log_BusinessOperate)
		{
			DAL.Add(log_BusinessOperate);
            BizLogHelper.AddOperate(log_BusinessOperate);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(Log_BusinessOperate log_BusinessOperate)
		{
            //修改前信息
            Log_BusinessOperate originalEntity=GetById(log_BusinessOperate.BizLogID);
			DAL.Save(log_BusinessOperate);
            BizLogHelper.UpdateOperate(originalEntity,log_BusinessOperate);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Int64 bizLogID)
		{
            doRemove(bizLogID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Int64[] bizLogIDs)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (Int64 id in bizLogIDs  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public Log_BusinessOperate GetById(Int64 bizLogID)
		{
			Log_BusinessOperate log_BusinessOperate = DAL.GetById(bizLogID);
			if (log_BusinessOperate == null)
			{
				throw new ETMS.AppContext.BusinessException("Security.Log_BusinessOperate.NotFoundException",new object[]{bizLogID});
			}
			
			return log_BusinessOperate;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<Log_BusinessOperate> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

