//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETMS.Components.Point.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BizErrorDefine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BizErrorDefine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ETMS.Components.Point.API.BizErrorDefine", typeof(BizErrorDefine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该数据已经使用，无法删除！.
        /// </summary>
        public static string Dic_PointReasonType_DataUsed {
            get {
                return ResourceManager.GetString("Dic_PointReasonType_DataUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该“课程积分规则”已经存在，无法保存，请重新输入！.
        /// </summary>
        public static string Index_UT_Point_Student_CourseRole {
            get {
                return ResourceManager.GetString("Index_UT_Point_Student_CourseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该【{0}】积分原因已经存在，无法保存，请重新输入！.
        /// </summary>
        public static string IX_Dic_PointReasonType_TypeName_Exists {
            get {
                return ResourceManager.GetString("IX_Dic_PointReasonType_TypeName_Exists", resourceCulture);
            }
        }
    }
}
