<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/MPageTree.master" AutoEventWireup="true"
    CodeFile="CourseOpenRange.aspx.cs" Inherits="Resource_CourseOpenRange_CourseOpenRange" %>

<asp:Content runat="server" ID="PageContent" ContentPlaceHolderID="ContentPlaceHolder1">
    <div class="dv_GradeviewList">
        <table class="" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <th style="width: 60px">
                    课程编码：
                </th>
                <td style="width: 100px">
                    <asp:Label ID="lblCourseCode" runat="server"></asp:Label>
                </td>
                <th style="width: 60px">
                    课程名称：
                </th>
                <td>
                    <asp:Label ID="lblCourseName" runat="server"></asp:Label>
                </td>
            </tr>
        </table>
    </div>
    <div class="dv_searchlist">
        <div class="dv_treeView" id="dv_treeView" style="height: 302px; overflow-x: hidden;
            overflow-y: auto;">
            <!--成员分级列表 -->
            <asp:TreeView runat="server" ID="lsMember" Width="96%" ShowCheckBoxes="All" ShowLines="true"
                AutoGenerateDataBindings="False" SelectedNodeStyle-BorderColor="black" SelectedNodeStyle-ForeColor="White"
                NodeStyle-ForeColor="#313131">
                <SelectedNodeStyle BorderColor="Black" Font-Bold="True" BackColor="Gray" ForeColor="White">
                </SelectedNodeStyle>
            </asp:TreeView>
        </div>
    </div>
    <div class="dv_submit">
        <asp:Button runat="server" ID="btnSave" Text="保存" OnClick="btnSave_Click" SkinID="Ok" /><asp:Button
            ID="btnReturn" runat="server" SkinID="Return" Text="取消" OnClientClick="closeWindow()" />
    </div>
    <script language="javascript" type="text/javascript">
        function public_GetParentByTagName(element, tagName) {
            var parent = element.parentNode;
            var upperTagName = tagName.toUpperCase();
            //如果这个元素还不是想要的tag就继续上溯
            while (parent && (parent.tagName.toUpperCase() != upperTagName)) {
                parent = parent.parentNode ? parent.parentNode : parent.parentElement;
            }
            return parent;
        }
        //设置节点的父节点Cheched——该节点可访问，则他的父节点也必能访问
        function setParentChecked(objNode) {
            var objParentDiv = public_GetParentByTagName(objNode, "div");
            if (objParentDiv == null || objParentDiv == "undefined") {
                return;
            }
            var objID = objParentDiv.getAttribute("ID");
            objID = objID.substring(0, objID.indexOf("Nodes"));
            objID = objID + "CheckBox";
            var objParentCheckBox = document.getElementById(objID);
            if (objParentCheckBox == null || objParentCheckBox == "undefined") {
                return;
            }
            if (objParentCheckBox.tagName != "INPUT" && objParentCheckBox.type == "checkbox")
                return;
            objParentCheckBox.checked = true;
            setParentChecked(objParentCheckBox);
        }
        //设置节点的子节点uncheched——该节点不可访问，则他的子节点也不能访问
        function setChildUnChecked(divID) {
            var objchild = divID.children;
            var count = objchild.length;
            for (var i = 0; i < objchild.length; i++) {
                var tempObj = objchild[i];
                if (tempObj.tagName == "INPUT" && tempObj.type == "checkbox") {
                    tempObj.checked = false;
                }
                setChildUnChecked(tempObj);
            }
        }
        //设置节点的子节点cheched——该节点可以访问，则他的子节点也都能访问
        function setChildChecked(divID) {
            var objchild = divID.children;
            var count = objchild.length;
            for (var i = 0; i < objchild.length; i++) {
                var tempObj = objchild[i];
                if (tempObj.tagName == "INPUT" && tempObj.type == "checkbox") {
                    tempObj.checked = true;
                }
                setChildChecked(tempObj);
            }
        }
        //触发事件
        function CheckEvent() {
            var objNode = event.srcElement;
            if (objNode.tagName != "INPUT" || objNode.type != "checkbox")
                return;
            if (objNode.checked == true) {
                setParentChecked(objNode);
                var objID = objNode.getAttribute("ID");
                var objID = objID.substring(0, objID.indexOf("CheckBox"));
                var objParentDiv = document.getElementById(objID + "Nodes");
                if (objParentDiv == null || objParentDiv == "undefined") {
                    return;
                }
                setChildChecked(objParentDiv);
            }
            else {
                var objID = objNode.getAttribute("ID");
                var objID = objID.substring(0, objID.indexOf("CheckBox"));
                var objParentDiv = document.getElementById(objID + "Nodes");
                if (objParentDiv == null || objParentDiv == "undefined") {
                    return;
                }
                setChildUnChecked(objParentDiv);
            }
        }
    </script>
</asp:Content>
