//==================================================================================================
//Version 1.0, auto-generated.
//Generated By huangzhf.
//Date: 2012-5-23 16:11:37.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;

using ETMS.AppContext;
namespace ETMS.Components.Basic.API.Entity.TrainingItem.Course
{
    /// <summary>
    /// 培训项目课程表业务实体
    /// </summary>
    [Serializable]
	public partial class Tr_ItemCourse:AbstractObject
	{ 	
        #region 所有业务基类
		 
        public override string DefaultKeyName
        {
            get { return "TrainingItemCourseID"; }
        }
         public override object KeyValue
        {
            get
            {
                return this.TrainingItemCourseID; 
            }
            set
            {
                this.TrainingItemCourseID=(Guid)value;
            }
        }    
	    #endregion

		#region Fields, Properties
		/// <summary>
		/// 培训项目课程ID
		/// </summary>
		public Guid TrainingItemCourseID{get;set;} 
		
		/// <summary>
		/// 培训项目ID
		/// </summary>
		public Guid TrainingItemID{get;set;} 
		
		/// <summary>
		/// 课程ID
		/// </summary>
		public Guid CourseID{get;set;} 
		
		/// <summary>
		/// 授课方式
		/// </summary>
		public Int32 TeachModelID{get;set;} 
		
		/// <summary>
		/// 课程状态
		/// </summary>
		public Int32 CourseStatus{get;set;} 
		
		/// <summary>
		/// 培训开始时间
		/// </summary>
		public DateTime CourseBeginTime{get;set;} 
		
		/// <summary>
		/// 培训结束时间
		/// </summary>
		public DateTime CourseEndTime{get;set;} 
		
		/// <summary>
		/// 培训方式
		/// </summary>
		public Int32 TrainingModelID{get;set;} 
		
		/// <summary>
		/// 外部培训机构ID
		/// </summary>
		public Guid OuterOrgID{get;set;} 
		
		/// <summary>
		/// 外部培训机构联系人
		/// </summary>
		public String OuterOrgDutyUser{get;set;} 
		
		/// <summary>
		/// 外部培训机构邮箱
		/// </summary>
		public String OuterOrgEMAIL{get;set;} 
		
		/// <summary>
		/// 课程属性
		/// </summary>
		public Int32 CourseAttrID{get;set;} 
		
		/// <summary>
		/// 积分
		/// </summary>
		public Int32 Score{get;set;} 
		
		/// <summary>
		/// 课时
		/// </summary>
		public Decimal CourseHours{get;set;} 
		
		/// <summary>
		/// 预算
		/// </summary>
		public Decimal BudgetFee{get;set;} 
		
		/// <summary>
		/// 备注
		/// </summary>
		public String Remark{get;set;} 
		
		/// <summary>
		/// 是否需要单独申请
		/// </summary>
		public Boolean IsNeedApply{get;set;} 
		
		/// <summary>
		/// 是否计划内课程
		/// </summary>
		public Boolean IsPlanCourse{get;set;} 
		
		/// <summary>
		/// 是否限制人数
		/// </summary>
		public Boolean IsLimit{get;set;} 
		
		/// <summary>
		/// 最大人数
		/// </summary>
		public Int32 MaxNum{get;set;} 
		
		/// <summary>
		/// 是否录入成绩
		/// </summary>
		public Boolean IsInputGrade{get;set;} 
		
		/// <summary>
		/// 是否发布成绩
		/// </summary>
		public Boolean IsIssueGrade{get;set;} 
		
		/// <summary>
		/// 成绩发布时间
		/// </summary>
		public DateTime GradeIssueTime{get;set;} 
		
		/// <summary>
		/// 成绩发布人
		/// </summary>
		public String GradeIssueUser{get;set;} 
		
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public Int32 CreateUserID{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public String CreateUser{get;set;} 
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime ModifyTime{get;set;} 
		
		/// <summary>
		/// 修改人
		/// </summary>
		public String ModifyUser{get;set;} 
		
		/// <summary>
		/// 删除标识
		/// </summary>
		public Boolean DelFlag{get;set;} 
		
		/// <summary>
		/// 及格线
		/// </summary>
		public Decimal PassLine{get;set;} 
		
		/// <summary>
		/// 总分
		/// </summary>
		public Decimal TotalScore{get;set;} 
		
		/// <summary>
		/// 是否发布积分
		/// </summary>
		public Boolean IsIssueScore{get;set;} 
		
		/// <summary>
		/// 积分发布人
		/// </summary>
		public String ScoreIssueUser{get;set;} 
		
		/// <summary>
		/// 积分发布时间
		/// </summary>
		public DateTime ScoreIssueTime{get;set;} 
		
		/// <summary>
		/// 是否已计算积分
		/// </summary>
		public Boolean IsComputeScore{get;set;} 
		
		/// <summary>
		/// 积分计算人
		/// </summary>
		public String ScoreComputeUser{get;set;} 
		
		/// <summary>
		/// 积分计算时间
		/// </summary>
		public DateTime ScoreComputeTime{get;set;} 
        
		/// <summary>
		/// 排序号
		/// </summary>
        public int OrderNum { get; set; } 
        
		
		#endregion Fields, Properties

	}
}
