//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2008-9-27 9:48:43.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;

using System.Data.SqlClient;
using ETMS.Utility.Data;

using ETMS.Components.Basic.API.Entity.Security;

namespace ETMS.Components.Basic.Implement.DAL.Security
{
    /// <summary>
    /// 数据访问
    /// </summary>
    public class RoleEnvironmentDataAccess : ETMS.Components.Basic.Implement.DAL.Common.IDataAccess
    {
        private static string SelectSql = @"
  SELECT * FROM
(
  SELECT 
       [RoleEnvironmentID]
      ,[RoleID]
      ,[EnvironmentID]
      ,[Creator]
      ,[CreateTime]
      ,(select RoleCode from dbo.Site_Role where Site_Role.[RoleID]=A.[RoleID]) AS RoleCode
	  ,B.ID AS SiteID
	  ,C.ID AS TypeID
  FROM dbo.[Site_Role_Environment] A 
    inner join dbo.Site_Environment B ON A.EnvironmentID=ID
	inner join dbo.Site_EnvironmentType C ON B.Type=C.TypeCode
) result WHERE 1=1 ";

        private static string MapSelectSql = @"
  SELECT 
       [RoleEnvironmentID]
      ,A.[RoleID]
      ,[EnvironmentID]
      ,A.[Creator]
      ,A.[CreateTime]
  FROM [Site_Role_Environment] A	
    inner join dbo.Site_Environment B ON A.EnvironmentID=ID
  WHERE 1=1 ";
        #region IDataAccess 成员

        public void Add(object obj)
        {
            RoleEnvironment roleEnvironment = (RoleEnvironment)obj;

            string commandName = "dbo.Pr_Site_Role_Environment_Insert";
            #region Parameters
            SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ETMSWrite, commandName);
            if (parms == null)
            {
                parms = new SqlParameter[] {	new SqlParameter("@RoleEnvironmentID", SqlDbType.Int, 4, ParameterDirection.Output, false, 0, 0, String.Empty, DataRowVersion.Default, null),
					new SqlParameter("@RoleID", SqlDbType.Int),
					new SqlParameter("@EnvironmentID", SqlDbType.Int),
					new SqlParameter("@Creator", SqlDbType.NVarChar, 50),
					new SqlParameter("@CreateTime", SqlDbType.DateTime)
					};
                SqlHelperParameterCache.CacheParameterSet(ConnectionString.ETMSWrite, commandName, parms);
            }

            parms[1].Value = roleEnvironment.RoleID;
            parms[2].Value = roleEnvironment.EnvironmentID;
            if (roleEnvironment.Creator != null) { parms[3].Value = roleEnvironment.Creator; } else { parms[3].Value = DBNull.Value; }
            parms[4].Value = roleEnvironment.CreateTime;
            #endregion
            SqlHelper.ExecuteNonQuery(ConnectionString.ETMSWrite, CommandType.StoredProcedure, commandName, parms);

            roleEnvironment.RoleEnvironmentID = (Int32)parms[0].Value;
        }

        public void Update(object obj)
        {
            RoleEnvironment roleEnvironment = (RoleEnvironment)obj;

            string commandName = "dbo.Pr_Site_Role_Environment_Update";
            #region Parameters
            SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ETMSWrite, commandName);
            if (parms == null)
            {
                parms = new SqlParameter[] {
					new SqlParameter("@RoleEnvironmentID", SqlDbType.Int),
					new SqlParameter("@RoleID", SqlDbType.Int),
					new SqlParameter("@EnvironmentID", SqlDbType.Int),
					new SqlParameter("@Creator", SqlDbType.NVarChar, 50),
					new SqlParameter("@CreateTime", SqlDbType.DateTime)
				};
                SqlHelperParameterCache.CacheParameterSet(ConnectionString.ETMSWrite, commandName, parms);
            }

            parms[0].Value = roleEnvironment.RoleEnvironmentID;
            parms[1].Value = roleEnvironment.RoleID;
            parms[2].Value = roleEnvironment.EnvironmentID;
            if (roleEnvironment.Creator != null) { parms[3].Value = roleEnvironment.Creator; } else { parms[3].Value = DBNull.Value; }
            parms[4].Value = roleEnvironment.CreateTime;
            #endregion
            SqlHelper.ExecuteNonQuery(ConnectionString.ETMSWrite, CommandType.StoredProcedure, commandName, parms);
        }

        public void Delete(object obj)
        {
            RoleEnvironment roleEnvironment = (RoleEnvironment)obj;

            string commandName = "dbo.Pr_Site_Role_Environment_Delete";
            #region Parameters
            SqlParameter[] parms = SqlHelperParameterCache.GetCachedParameterSet(ConnectionString.ETMSWrite, commandName);
            if (parms == null)
            {
                parms = new SqlParameter[] {
					new SqlParameter("@RoleEnvironmentID", SqlDbType.Int)
				};
                SqlHelperParameterCache.CacheParameterSet(ConnectionString.ETMSWrite, commandName, parms);
            }

            parms[0].Value = roleEnvironment.RoleEnvironmentID;

            #endregion
            SqlHelper.ExecuteNonQuery(ConnectionString.ETMSWrite, CommandType.StoredProcedure, commandName, parms);
        }

        public object Query(object id)
        {
            Int32 roleEnvironmentID = (int)id;

            string sqlScriptFormat = SelectSql + " AND RoleEnvironmentID={0}";

            DataTable dt = SqlHelper.ExecuteDataset(ConnectionString.ETMSRead, CommandType.Text, string.Format(sqlScriptFormat, roleEnvironmentID)).Tables[0];
            if (dt.Rows.Count == 0)
                return null;
            return RoleEnvironment.ConvertDataRowToRoleEnvironment(dt.Rows[0]);
        }

        public Object[] Query(string filter)
        {
            string sqlScriptFormat = (filter.IndexOf("Type", StringComparison.InvariantCultureIgnoreCase) == -1 ? SelectSql + " {0} order by TypeID,SiteID " : MapSelectSql + " {0} order by B.ID ");

            List<RoleEnvironment> list = new List<RoleEnvironment>();
            foreach (DataRow row in SqlHelper.ExecuteDataset(ConnectionString.ETMSRead, CommandType.Text, string.Format(sqlScriptFormat, filter)).Tables[0].Rows)
            {
                list.Add(RoleEnvironment.ConvertDataRowToRoleEnvironment(row));
            }

            return (Object[])list.ToArray();
        }

        public Object[] Query(int pageIndex, int pageSize, string filter, string orderBy, out int recordCount)
        {
            throw new Exception("The method or operation is not implemented.");
        }

        #endregion
    }
}
