//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-4-17 15:53:39.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.Poll.API.Entity;
using ETMS.Components.Poll.Implement.DAL;
namespace ETMS.Components.Poll.Implement.BLL
{
    /// <summary>
    /// 调查题型表业务逻辑
    /// </summary>
    public partial class Poll_TitleTypeLogic
	{
		private static readonly Poll_TitleTypeDataAccess DAL = new Poll_TitleTypeDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(Poll_TitleType poll_TitleType)
		{
			DAL.Add(poll_TitleType);
            BizLogHelper.AddOperate(poll_TitleType);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(Poll_TitleType poll_TitleType)
		{
            //修改前信息
            Poll_TitleType originalEntity=GetById(poll_TitleType.TitleTypeID);
			DAL.Save(poll_TitleType);
            BizLogHelper.UpdateOperate(originalEntity,poll_TitleType);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Int32 titleTypeID)
		{
            doRemove(titleTypeID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Int32[] titleTypeIDs)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (Int32 id in titleTypeIDs  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public Poll_TitleType GetById(Int32 titleTypeID)
		{
			Poll_TitleType poll_TitleType = DAL.GetById(titleTypeID);
			if (poll_TitleType == null)
			{
				throw new ETMS.AppContext.BusinessException(".Poll_TitleType.NotFoundException",new object[]{titleTypeID});
			}
			
			return poll_TitleType;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<Poll_TitleType> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

