//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-4-17 15:53:39.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using ETMS.Utility;
using ETMS.Utility.Logging;
using ETMS.Components.Poll.API.Entity;
namespace ETMS.Components.Poll.Implement.BLL
{
    /// <summary>
    /// 业务逻辑
    /// </summary>
    public partial class Poll_ResourceTypeLogic
	{
 		/// <summary>
		/// 保存操作
		/// </summary>
		public void Save(Poll_ResourceType poll_ResourceType)
		{
            try
            {
			    if(poll_ResourceType.ResourceTypeCode.IsEmpty())
                {
                    //设置主键ID（仅类型为GUID有效，Int型则由数据库自增产生）
                    poll_ResourceType.ResourceTypeCode=poll_ResourceType.ResourceTypeCode.NewID();;
                    Add(poll_ResourceType);
                }
                else
                {
                    Update(poll_ResourceType);
                }
            }
           catch (System.Data.SqlClient.SqlException ex)
            {
                //枚举数据约束异常并转换为业务异常
                if (ex.Message.IndexOf("Index_U_Poll_ResourceTypeCode",StringComparison.InvariantCultureIgnoreCase) != -1)
                {
				    throw new ETMS.AppContext.BusinessException(".Poll_ResourceType.CodeExists");
                }
                else if (ex.Message.IndexOf("Index_U_Poll_ResourceTypeName",StringComparison.InvariantCultureIgnoreCase) != -1)
                {
				    throw new ETMS.AppContext.BusinessException(".Poll_ResourceType.NameExists");
                }
                //如果仍未处理，则抛出
                throw ex;
            } 
		} 

        /// <summary>
		/// 删除
		/// </summary>
		protected void doRemove(String resourceTypeCode)
		{
            try
            {
			     DAL.Remove(resourceTypeCode);
                 //记录删除日志（根据ID删除）
                 BizLogHelper.Operate(resourceTypeCode,"删除");
            }
           catch (System.Data.SqlClient.SqlException ex)
            {
                //枚举数据约束异常并转换为业务异常，数据已经使用
                if (ex.Message.IndexOf("FK_",StringComparison.InvariantCultureIgnoreCase) != -1)
                {
				    throw new ETMS.AppContext.BusinessException(".Poll_ResourceType.DataUsed");
                } 
                //如果仍未处理，则抛出
                throw ex;
            }  
		}  
	}
	
	
}

