//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-4-17 15:53:39.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.Poll.API.Entity;
using ETMS.Components.Poll.Implement.DAL;
using System.Transactions;
namespace ETMS.Components.Poll.Implement.BLL
{
    /// <summary>
    /// 业务逻辑
    /// </summary>
    public partial class Poll_ResourceTypeLogic
	{
		private static readonly Poll_ResourceTypeDataAccess DAL = new Poll_ResourceTypeDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(Poll_ResourceType poll_ResourceType)
		{
			DAL.Add(poll_ResourceType);
            BizLogHelper.AddOperate(poll_ResourceType);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(Poll_ResourceType poll_ResourceType)
		{
            //修改前信息
            Poll_ResourceType originalEntity=GetById(poll_ResourceType.ResourceTypeCode);
			DAL.Save(poll_ResourceType);
            BizLogHelper.UpdateOperate(originalEntity,poll_ResourceType);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(String resourceTypeCode)
		{
            doRemove(resourceTypeCode);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(String[] resourceTypeCodes)
		{
#if !DEBUG
			using (TransactionScope ts = new TransactionScope())
			{
#endif
				foreach (String id in resourceTypeCodes  )
				{
					Remove(id);
				}
#if !DEBUG
				ts.Complete();
			}
#endif
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public Poll_ResourceType GetById(String resourceTypeCode)
		{
			Poll_ResourceType poll_ResourceType = DAL.GetById(resourceTypeCode);
			if (poll_ResourceType == null)
			{
				throw new ETMS.AppContext.BusinessException(".Poll_ResourceType.NotFoundException",new object[]{resourceTypeCode});
			}
			
			return poll_ResourceType;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<Poll_ResourceType> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

