//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-5-6 11:46:50.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;
using System.Collections.Generic;
using System.Data;
using ETMS.Utility.Logging;
using ETMS.Components.IDP.API.Entity;
using ETMS.Components.IDP.Implement.DAL;
namespace ETMS.Components.IDP.Implement.BLL
{
    /// <summary>
    /// IDP计划目标反馈表业务逻辑
    /// </summary>
    public partial class IDP_PlanObjectFeedbackLogic
	{
		private static readonly IDP_PlanObjectFeedbackDataAccess DAL = new IDP_PlanObjectFeedbackDataAccess();
		
		/// <summary>
		/// 增加
		/// </summary>
		public void Add(IDP_PlanObjectFeedback iDP_PlanObjectFeedback)
		{
			DAL.Add(iDP_PlanObjectFeedback);
            BizLogHelper.AddOperate(iDP_PlanObjectFeedback);
		}


		/// <summary>
		/// 保存
		/// </summary>
		public void Update(IDP_PlanObjectFeedback iDP_PlanObjectFeedback)
		{
            //修改前信息
            IDP_PlanObjectFeedback originalEntity=GetById(iDP_PlanObjectFeedback.IDPPlanObjectFeedbackID);
			DAL.Save(iDP_PlanObjectFeedback);
            BizLogHelper.UpdateOperate(originalEntity,iDP_PlanObjectFeedback);
		}

		/// <summary>
		/// 删除
		/// </summary>
		public void Remove(Guid iDPPlanObjectFeedbackID)
		{
            doRemove(iDPPlanObjectFeedbackID);
		} 

		/// <summary>
		/// 批量删除(主键ID数组）
		/// </summary>
		public void Remove(Guid[] iDPPlanObjectFeedbackIDs)
		{
				foreach (Guid id in iDPPlanObjectFeedbackIDs  )
				{
					Remove(id);
				}
		} 
    
    
		/// <summary>
		/// 根据标识获取对象
		/// </summary>
		public IDP_PlanObjectFeedback GetById(Guid iDPPlanObjectFeedbackID)
		{
			IDP_PlanObjectFeedback iDP_PlanObjectFeedback = DAL.GetById(iDPPlanObjectFeedbackID);
			if (iDP_PlanObjectFeedback == null)
			{
				throw new ETMS.AppContext.BusinessException("IDP.IDP_PlanObjectFeedback.NotFoundException",new object[]{iDPPlanObjectFeedbackID});
			}
			
			return iDP_PlanObjectFeedback;
		}		
		 
		/// <summary>
        /// 查询数据列表分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public DataTable GetPagedList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetPagedList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
				
        /// <summary>
        /// 查询实体分页数据
        /// </summary>
        /// <param name="pageIndex">页号</param>
        /// <param name="pageSize">页面大小</param>
        /// <param name="sortExpression">排序条件</param>
        /// <param name="criteria">筛选条件</param>
        /// <param name="totalRecords">out 记录总数</param>
        /// <returns>返回查询结果</returns>
		public IList<IDP_PlanObjectFeedback> GetEntityList(int pageIndex, int pageSize, string sortExpression, string criteria,out int totalRecords)
		{				
			return DAL.GetEntityList(pageIndex, pageSize, sortExpression, criteria, out totalRecords);
		}
		
	}
	
	
}

