//==================================================================================================
//Version 1.0, auto-generated.
//Generated By xueyb.
//Date: 2012-04-18 22:30:53.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1), a product of ZhouYonghua(Zhou_Yonghua@163.com).
//==================================================================================================

using System;

using ETMS.AppContext;
namespace ETMS.Components.StudyClass.API.Entity.StudyClass
{
    /// <summary>
    /// 班级群组学员表业务实体
    /// </summary>
    [Serializable]
	public partial class Sty_ClassSubgroupStudent:AbstractObject
	{ 	
        #region 所有业务基类
		 
        public override string DefaultKeyName
        {
            get { return "SubgroupStudentID"; }
        }
         public override object KeyValue
        {
            get
            {
                return this.SubgroupStudentID; 
            }
            set
            {
                this.SubgroupStudentID=(Guid)value;
            }
        }    
	    #endregion

		#region Fields, Properties
		/// <summary>
		/// 班级群组学员ID
		/// </summary>
		public Guid SubgroupStudentID{get;set;} 
		
		/// <summary>
		/// 班级群组ID
		/// </summary>
		public Guid ClassSubgroupID{get;set;} 
		
		/// <summary>
		/// 班级学员ID
		/// </summary>
		public Guid ClassStudentID{get;set;} 
		
		/// <summary>
		/// 是否是队长
		/// </summary>
		public Boolean IsLeader{get;set;} 
		
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public Int32 CreateUserID{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public String CreateUser{get;set;} 
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime ModifyTime{get;set;} 
		
		/// <summary>
		/// 修改人
		/// </summary>
		public String ModifyUser{get;set;} 
		
		/// <summary>
		/// 备注
		/// </summary>
		public String Remark{get;set;} 
		
		#endregion Fields, Properties

	}
}
