//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-04-18 22:30:52.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================


using ETMS.AppContext;
namespace ETMS.Components.StudyClass.API.Entity.StudyClass
{
    /// <summary>
    /// 班级表业务实体
    /// </summary>
    public partial class Sty_Class:AbstractObject
	{
        public int StudentTypeID { get; set; }
        public int AssignCount { get; set; }
	}
}
