//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-04-18 22:30:53.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;

using ETMS.AppContext;
namespace ETMS.Components.StudyClass.API.Entity.StudyClass
{
    /// <summary>
    /// 班级群组表业务实体
    /// </summary>
    [Serializable]
	public partial class Sty_ClassSubgroup:AbstractObject
	{ 	
        #region 所有业务基类
		 
        public override string DefaultKeyName
        {
            get { return "ClassSubgroupID"; }
        }
         public override object KeyValue
        {
            get
            {
                return this.ClassSubgroupID; 
            }
            set
            {
                this.ClassSubgroupID=(Guid)value;
            }
        }    
	    #endregion

		#region Fields, Properties
		/// <summary>
		/// 班级群组ID
		/// </summary>
		public Guid ClassSubgroupID{get;set;} 
		
		/// <summary>
		/// 班级ID
		/// </summary>
		public Guid ClassID{get;set;} 
		
		/// <summary>
		/// 班级群组名称
		/// </summary>
		public String ClassSubgroupName{get;set;} 
		
		/// <summary>
		/// 群主说明
		/// </summary>
		public String ClassSubgroupDesc{get;set;} 
		
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public Int32 CreateUserID{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public String CreateUser{get;set;} 
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime ModifyTime{get;set;} 
		
		/// <summary>
		/// 修改人
		/// </summary>
		public String ModifyUser{get;set;} 
		
		/// <summary>
		/// 备注
		/// </summary>
		public String Remark{get;set;} 
		
		#endregion Fields, Properties

	}
}
