//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-4-17 15:53:39.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;

using ETMS.AppContext;
namespace ETMS.Components.Poll.API.Entity
{
    /// <summary>
    /// 选项表业务实体
    /// </summary>
    [Serializable]
	public partial class Poll_Option:AbstractObject
	{ 	
        #region 所有业务基类
		 
        public override string DefaultKeyName
        {
            get { return "OptionID"; }
        }
         public override object KeyValue
        {
            get
            {
                return this.OptionID; 
            }
            set
            {
                this.OptionID=(Int32)value;
            }
        }    
	    #endregion

		#region Fields, Properties
		/// <summary>
		/// 选项编号
		/// </summary>
		public Int32 OptionID{get;set;} 
		
		/// <summary>
		/// 题目编号
		/// </summary>
		public Int32 TitleID{get;set;} 
		
		/// <summary>
		/// 选项名称
		/// </summary>
		public String OptionName{get;set;} 
		
		/// <summary>
		/// 其他选项文本长度
		/// </summary>
		public Int32 OtherLength{get;set;} 
		
		#endregion Fields, Properties

	}
}
