//==================================================================================================
//Version 1.0, auto-generated.
//Generated By running1218
//Date: 2012-4-17 15:53:39.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1)
//==================================================================================================

using System;

using ETMS.AppContext;
namespace ETMS.Components.Poll.API.Entity
{
    /// <summary>
    /// 业务实体
    /// </summary>
    [Serializable]
    public partial class Poll_QueryPublishObject : AbstractObject
    {
        #region 所有业务基类

        public override string DefaultKeyName
        {
            get { return "QueryPublishID"; }
        }
        public override object KeyValue
        {
            get
            {
                return this.QueryPublishID;
            }
            set
            {
                this.QueryPublishID = (Int32)value;
            }
        }
        #endregion

        #region Fields, Properties
        /// <summary>
        /// 调查发布对象编号
        /// </summary>
        public Int32 QueryPublishID { get; set; }

        /// <summary>
        /// 资源代码
        /// </summary>
        public String ResourceCode { get; set; }

        /// <summary>
        /// 调查编号
        /// </summary>
        public Int32 QueryID { get; set; }

        /// <summary>
        /// 资源类型编码
        /// </summary>
        public String ResourceTypeCode { get; set; }

        /// <summary>
        /// 分析报告文件名称
        /// </summary>
        public String FileName { get; set; }

        /// <summary>
        /// 分析报告路径
        /// </summary>
        public String FilePath { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        public String Creator { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 修改人
        /// </summary>
        public String Modifier { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime ModifiyTime { get; set; }

        /// <summary>
        /// 综合分数
        /// </summary>
        public Int32 Score { get; set; }

        #endregion Fields, Properties

    }
}
