//==================================================================================================
//Version 1.0, auto-generated.
//Generated By huangzhf.
//Date: 2012-5-23 16:17:38.
//==================================================================================================
//==================================================================================================
//This file is generated by CodeGenerator(Ver 2.1), a product of ZhouYonghua(Zhou_Yonghua@163.com).
//==================================================================================================

using System;

using ETMS.AppContext;
namespace ETMS.Components.Basic.API.Entity.TrainingPlan
{
    /// <summary>
    /// 培训计划表业务实体
    /// </summary>
    [Serializable]
	public partial class Tr_Plan:AbstractObject
	{ 	
        #region 所有业务基类
		 
        public override string DefaultKeyName
        {
            get { return "PlanID"; }
        }
         public override object KeyValue
        {
            get
            {
                return this.PlanID; 
            }
            set
            {
                this.PlanID=(Guid)value;
            }
        }    
	    #endregion

		#region Fields, Properties
		/// <summary>
		/// 培训计划ID
		/// </summary>
		public Guid PlanID{get;set;} 
		
		/// <summary>
		/// 所属机构ID
		/// </summary>
		public Int32 OrgID{get;set;} 
		
		/// <summary>
		/// 培训级别
		/// </summary>
		public Int32 TrainingLevelID{get;set;} 
		
		/// <summary>
		/// 计划类型
		/// </summary>
		public Int32 PlanTypeID{get;set;} 
		
		/// <summary>
		/// 专业类别编码
		/// </summary>
		public String SpecialtyTypeCode{get;set;} 
		
		/// <summary>
		/// 计划编码
		/// </summary>
		public String PlanCode{get;set;} 
		
		/// <summary>
		/// 计划名称
		/// </summary>
		public String PlanName{get;set;} 
		
		/// <summary>
		/// 是否启用
		/// </summary>
		public Int32 IsUse{get;set;} 
		
		/// <summary>
		/// 计划开始时间
		/// </summary>
		public DateTime PlanBeginTime{get;set;} 
		
		/// <summary>
		/// 计划结束时间
		/// </summary>
		public DateTime PlanEndTime{get;set;} 
		
		/// <summary>
		/// 负责人
		/// </summary>
		public String DutyUser{get;set;} 
		
		/// <summary>
		/// 手机
		/// </summary>
		public String Mobile{get;set;} 
		
		/// <summary>
		/// 邮箱
		/// </summary>
		public String EMAIL{get;set;} 
		
		/// <summary>
		/// 预算
		/// </summary>
		public Decimal BudgetFee{get;set;} 
		
		/// <summary>
		/// 计划学员数
		/// </summary>
		public Int32 StudentNum{get;set;} 
		
		/// <summary>
		/// 计划目标
		/// </summary>
		public String PlanTarget{get;set;} 
		
		/// <summary>
		/// 目标学员
		/// </summary>
		public String PlanObjectStudent{get;set;} 
		
		/// <summary>
		/// 备注
		/// </summary>
		public String Remark{get;set;} 
		
		/// <summary>
		/// 组织部门ID
		/// </summary>
		public Int32 DutyDeptID{get;set;} 
		
		/// <summary>
		/// 计划状态
		/// </summary>
		public Int32 PlanStatus{get;set;} 
		
		/// <summary>
		/// 审核人
		/// </summary>
		public String AuditUser{get;set;} 
		
		/// <summary>
		/// 审核时间
		/// </summary>
		public DateTime AuditTime{get;set;} 
		
		/// <summary>
		/// 审核意见
		/// </summary>
		public String AuditOpinion{get;set;} 
		
		/// <summary>
		/// 计划结束备注
		/// </summary>
		public String PlanEndRemark{get;set;} 
		
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public Int32 CreateUserID{get;set;} 
		
		/// <summary>
		/// 创建人
		/// </summary>
		public String CreateUser{get;set;} 
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime ModifyTime{get;set;} 
		
		/// <summary>
		/// 修改人
		/// </summary>
		public String ModifyUser{get;set;} 
		
		/// <summary>
		/// 删除标识
		/// </summary>
		public Boolean DelFlag{get;set;} 
		
		/// <summary>
		/// 项目归档方式
		/// </summary>
		public Int32 PlanEndModeID{get;set;} 
		
		#endregion Fields, Properties

	}
}
